// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/hyperledger/fabric-chaincode-go/v2/pkg/cid"
	x509 "crypto/x509"
)

// ClientIdentity is a mock implementation of cid.ClientIdentity
type ClientIdentity struct {
	GetMSPIDStub        func() (string, error)
	getMSPIDMutex       sync.RWMutex
	getMSPIDArgsForCall []struct{}
	getMSPIDReturns     struct {
		result1 string
		result2 error
	}

	GetIDStub        func() (string, error)
	getIDMutex       sync.RWMutex
	getIDArgsForCall []struct{}
	getIDReturns     struct {
		result1 string
		result2 error
	}

	GetX509CertificateStub        func() (*x509.Certificate, error)
	getX509CertificateMutex       sync.RWMutex
	getX509CertificateArgsForCall []struct{}
	getX509CertificateReturns     struct {
		result1 *x509.Certificate
		result2 error
	}

	AssertAttributeValueStub        func(string, string) error
	assertAttributeValueMutex       sync.RWMutex
	assertAttributeValueArgsForCall []struct {
		arg1 string
		arg2 string
	}
	assertAttributeValueReturns struct {
		result1 error
	}

	GetAttributeValueStub        func(string) (string, bool, error)
	getAttributeValueMutex       sync.RWMutex
	getAttributeValueArgsForCall []struct {
		arg1 string
	}
	getAttributeValueReturns struct {
		result1 string
		result2 bool
		result3 error
	}

	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

// Ensure ClientIdentity implements cid.ClientIdentity
var _ cid.ClientIdentity = new(ClientIdentity)

func (fake *ClientIdentity) GetMSPID() (string, error) {
	fake.getMSPIDMutex.Lock()
	fake.getMSPIDArgsForCall = append(fake.getMSPIDArgsForCall, struct{}{})
	fake.getMSPIDMutex.Unlock()
	return fake.getMSPIDReturns.result1, fake.getMSPIDReturns.result2
}

func (fake *ClientIdentity) GetMSPIDReturns(result1 string, result2 error) {
	fake.getMSPIDMutex.Lock()
	defer fake.getMSPIDMutex.Unlock()
	fake.GetMSPIDStub = nil
	fake.getMSPIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ClientIdentity) GetID() (string, error) {
	fake.getIDMutex.Lock()
	fake.getIDArgsForCall = append(fake.getIDArgsForCall, struct{}{})
	fake.getIDMutex.Unlock()
	return fake.getIDReturns.result1, fake.getIDReturns.result2
}

func (fake *ClientIdentity) GetIDReturns(result1 string, result2 error) {
	fake.getIDMutex.Lock()
	defer fake.getIDMutex.Unlock()
	fake.getIDReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *ClientIdentity) GetX509Certificate() (*x509.Certificate, error) {
	fake.getX509CertificateMutex.Lock()
	fake.getX509CertificateArgsForCall = append(fake.getX509CertificateArgsForCall, struct{}{})
	fake.getX509CertificateMutex.Unlock()
	return fake.getX509CertificateReturns.result1, fake.getX509CertificateReturns.result2
}

func (fake *ClientIdentity) AssertAttributeValue(attr string, value string) error {
	fake.assertAttributeValueMutex.Lock()
	fake.assertAttributeValueArgsForCall = append(fake.assertAttributeValueArgsForCall, struct {
		arg1 string
		arg2 string
	}{attr, value})
	fake.assertAttributeValueMutex.Unlock()
	return fake.assertAttributeValueReturns.result1
}

func (fake *ClientIdentity) GetAttributeValue(attr string) (string, bool, error) {
	fake.getAttributeValueMutex.Lock()
	fake.getAttributeValueArgsForCall = append(fake.getAttributeValueArgsForCall, struct {
		arg1 string
	}{attr})
	fake.getAttributeValueMutex.Unlock()
	return fake.getAttributeValueReturns.result1, fake.getAttributeValueReturns.result2, fake.getAttributeValueReturns.result3
}
